credentials:
  uri: 'bolt://xx.xxx.23.80:xxxx'
  user: neo4j
  password: 'xxxx-xxxx-opposites'

cypher:
  load_nodes:

    # loading in the title.principals.tsv.gz nodes
    # WHERE row.tconst IS NOT NULL AND row.nconst IS NOT NULL
    load_series: | 
      WITH $rows AS rows
      UNWIND rows AS row
      MERGE (title_p:Title_principals {titleID: row.tconst})
      ON CREATE SET title_p.index_ = row.ordering, title_p.personID = row.nconst, title_p.job_category= row.category,
      title_p.job_title= row.job, title_p.characters_name= row.characters
